### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by yanffernandes** [mahmourad98/microsoft_clarity_flutter_plugin#1]
I’m trying to add clarity to my Flutter app. How can I install it?

**Comment by mahmourad98** [comment]
1. Add this dependency to your flutter project in 'pubspec.yaml' file, add this line under the dependencies scope
  microsoft_clarity_plugin:
    git: https://github.com/mahmourad98/microsoft_clarity_flutter_plugin.git
2. Add the project ID to Android string resources under the key 'microsoft_clarity_project_id'.
3. Add the project id into the iOS 'info.plist' file under the key 'MICROSOFT_CLARITY_PROJECT_ID'.
4. call the initialization method from the plugin in your main method or app entry point.
